### ISSUE TITLE
Not recognizing "call" or "ros2"... What can I do?

### ISSUE THREAD

**Issue by younesqsr** [LucaVits/LearningROSWithPythonTurtle#1]
![image](https://github.com/LucaVits/LearningROSWithPythonTurtle/assets/163776873/e46b19b1-b445-4ac1-ad8f-0000b161ac49)

Please help...

**Comment by LucaVits** [comment]
Hello! Can you please confirm that this is within an Administrator Command Prompt, and not an Administrator Powershell? This issue typically occurs if the command is run within Powershell. To enter a Command Prompt, go to your search bar and enter "CMD" instead of "Terminal" or "Powershell"
Below I have linked the two images which show the differences between the CMD and Powershell windows
![image](https://github.com/LucaVits/LearningROSWithPythonTurtle/assets/56119921/ac9a99f9-7051-4312-b44b-6a9b59c190f0)
![image](https://github.com/LucaVits/LearningROSWithPythonTurtle/assets/56119921/a95ead29-484e-44ed-a822-761b362576ff)
